name: intro
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

# 의존성 명시
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.11 # supabase
  image_picker: ^1.1.2 # image data
  flutter_naver_map: ^1.2.3+1 # naver map
  geolocator: ^12.0.0 # 주소 <-> 위경도 변환
  http: ^1.2.2 # http 요청 통신
  daum_postcode_search: ^0.0.2 # 다음 주소 검색
  flutter_inappwebview: ^5.8.0 # 다음 주소 검색 (웹뷰)
  intl: ^0.19.0 # DateFormat
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0

flutter:
  assets:
    - assets/
  uses-material-design: true
